#include "./_pure.hpp"
#include "./transparent.hpp"
#include "./constant.hpp"
#include "./linear.hpp"
#include "./quadratic.hpp"
#include "./exponential.hpp"

//#include "./wrapcb.cpp"
//#include "./wrapcb.hpp"
//#include "./wrapcptr.hpp"
//#include "./wrapfunct.hpp"