import box_render
import box_render
import cone_render
import cylinder_render
import disc_render
import paraboloid_render
import plane_render
import quadric_render
import sphere_render
import torus_render
import triangle_render
import usphere_render