import box_invoke
import box_invoke
import cone_invoke
import cylinder_invoke
import disc_invoke
import paraboloid_invoke
import plane_invoke
import quadric_invoke
import sphere_invoke
import torus_invoke
import triangle_invoke
import usphere_invoke