#include "./alp.hpp"
#include "./ambient.hpp"
#include "./as_diffuse.hpp"
#include "./as_specular.hpp"
#include "./beckmann.hpp"
#include "./blinn.hpp"

#include "./ct_fresnel.hpp"
#include "./ct_schlick.hpp"

#include "./gaussian.hpp"
#include "./hs_lambert.hpp"
#include "./hs_normal.hpp"
#include "./hs_phong.hpp"
#include "./lambert.hpp"
#include "./on_f29.hpp"
#include "./on_p44.hpp"
#include "./on_yf.hpp"
#include "./phong.hpp"
#include "./ward_approx.hpp"
#include "./ward_isotropic.hpp"
#include "./ward_real.hpp"
