%prg_python37%  core\geometry\blobby\uwaterZ.py
%prg_python37%  core\material\illumination\ward_real.py
%prg_python37%  core\material\illumination\ward_isotropic.py
%prg_python37%  core\material\illumination\ward_approx.py
%prg_python37%  core\render\2pierce\uv.py
%prg_python37%  core\render\1pixel\uv.py
%prg_python37%  core\geometry\blobby\usphere.py
%prg_python37%  core\geometry\simple\usphere\unit.py
%prg_python37%  core\geometry\simple\triangle\unit.py
%prg_python37%  core\geometry\simple\torus\unit.py
%prg_python37%  core\geometry\simple\sphere\unit.py
%prg_python37%  core\geometry\simple\paraboloid\unit.py
%prg_python37%  core\geometry\simple\disc\unit.py
%prg_python37%  core\geometry\simple\cylinder\unit.py
%prg_python37%  core\geometry\simple\cone\unit.py
%prg_python37%  core\geometry\simple\box\unit.py
%prg_python37%  core\geometry\rtss\uniform_render.py
%prg_python37%  core\geometry\rtss\uniform_invoke.py
%prg_python37%  core\geometry\blobby\ucylinderZ.py
%prg_python37%  core\light\type_Spot_invoke.py
%prg_python37%  core\geometry\transform\translate-render.py
%prg_python37%  core\geometry\transform\translate-invoke.py
%prg_python37%  core\geometry\simple\usphere\translate.py
%prg_python37%  core\geometry\simple\torus\translate.py
%prg_python37%  core\geometry\simple\sphere\translate.py
%prg_python37%  core\geometry\simple\plane\translate.py
%prg_python37%  core\geometry\simple\paraboloid\translate.py
%prg_python37%  core\geometry\simple\disc\translate.py
%prg_python37%  core\geometry\simple\cylinder\translate.py
%prg_python37%  core\geometry\simple\cone\translate.py
%prg_python37%  core\geometry\simple\box\translate.py
%prg_python37%  core\geometry\blobby\translate.py
%prg_python37%  core\camera\transform.py
%prg_python37%  core\object\material\test1.py
%prg_python37%  core\geometry\blobby\system.py
%prg_python37%  core\material\light\swarm1-invoke.py
%prg_python37%  core\material\surface.py
%prg_python37%  core\geometry\simple\surface.py
%prg_python37%  core\material\light\spotUVW-invoke.py
%prg_python37%  core\light\sphere_invoke.py
%prg_python37%  core\geometry\blobby\sphere.py
%prg_python37%  core\geometry\simple\usphere\solitary.py
%prg_python37%  core\geometry\simple\triangle\solitary.py
%prg_python37%  core\geometry\simple\torus\solitary.py
%prg_python37%  core\geometry\simple\sphere\solitary.py
%prg_python37%  core\geometry\simple\quadric\solitary.py
%prg_python37%  core\geometry\simple\plane\solitary.py
%prg_python37%  core\geometry\simple\paraboloid\solitary.py
%prg_python37%  core\geometry\simple\disc\solitary.py
%prg_python37%  core\geometry\simple\cylinder\solitary.py
%prg_python37%  core\geometry\simple\cone\solitary.py
%prg_python37%  core\geometry\simple\box\solitary.py
%prg_python37%  core\material\illumination\phong\render.py
%prg_python37%  core\material\illumination\lambert\render.py
%prg_python37%  core\material\illumination\gaussian\render.py
%prg_python37%  core\material\illumination\blinn\render.py
%prg_python37%  core\material\illumination\beckmann\render.py
%prg_python37%  core\material\illumination\ambient\render.py
%prg_python37%  core\light\sun\render.py
%prg_python37%  core\light\spline\render.py
%prg_python37%  core\light\reflector\render.py
%prg_python37%  core\light\point\render.py
%prg_python37%  core\light\line\render.py
%prg_python37%  core\light\circle\render.py
%prg_python37%  core\light\chandelier\render.py
%prg_python37%  core\light\blocked\render.py
%prg_python37%  core\geometry\complex\render.py
%prg_python37%  core\material\medium\quadratic.py
%prg_python37%  core\geometry\simple\usphere\plate.py
%prg_python37%  core\geometry\simple\triangle\plate.py
%prg_python37%  core\geometry\simple\torus\plate.py
%prg_python37%  core\geometry\simple\sphere\plate.py
%prg_python37%  core\geometry\simple\paraboloid\plate.py
%prg_python37%  core\geometry\simple\disc\plate.py
%prg_python37%  core\geometry\simple\cylinder\plate.py
%prg_python37%  core\geometry\simple\cone\plate.py
%prg_python37%  core\geometry\simple\box\plate.py
%prg_python37%  core\material\illumination\hs\phong_render.py
%prg_python37%  core\material\illumination\hs\phong_invoke.py
%prg_python37%  core\camera\flat\perspective.py
%prg_python37%  core\material\illumination\on\p44.py
%prg_python37%  core\camera\flat\orthogonal.py
%prg_python37%  core\material\transmission\reflect\one.py
%prg_python37%  core\geometry\rtss\objectlist_render.py
%prg_python37%  core\geometry\rtss\objectlist_invoke.py
%prg_python37%  core\object\object.py
%prg_python37%  core\geometry\simple\object.py
%prg_python37%  core\material\material.py
%prg_python37%  core\geometry\simple\sphere\make.py
%prg_python37%  core\geometry\simple\sphere\main.py
%prg_python37%  core\geometry\rtss\list_render.py
%prg_python37%  core\geometry\rtss\list_invoke.py
%prg_python37%  core\material\medium\linear.py
%prg_python37%  core\geometry\simple\light.py
%prg_python37%  core\material\illumination\hs\lambert_render.py
%prg_python37%  core\material\illumination\hs\lambert_invoke.py
%prg_python37%  core\light\area\lambert.py
%prg_python37%  core\material\illumination\phong\invoke.py
%prg_python37%  core\material\illumination\lambert\invoke.py
%prg_python37%  core\material\illumination\gaussian\invoke.py
%prg_python37%  core\material\illumination\blinn\invoke.py
%prg_python37%  core\material\illumination\beckmann\invoke.py
%prg_python37%  core\material\illumination\ambient\invoke.py
%prg_python37%  core\light\sun\invoke.py
%prg_python37%  core\light\spline\invoke.py
%prg_python37%  core\light\reflector\invoke.py
%prg_python37%  core\light\point\invoke.py
%prg_python37%  core\light\line\invoke.py
%prg_python37%  core\light\circle\invoke.py
%prg_python37%  core\light\chandelier\invoke.py
%prg_python37%  core\light\blocked\invoke.py
%prg_python37%  core\light\area\invoke.py
%prg_python37%  core\geometry\simple\usphere\invoke.py
%prg_python37%  core\geometry\simple\triangle\invoke.py
%prg_python37%  core\geometry\simple\torus\invoke.py
%prg_python37%  core\geometry\simple\sphere\invoke.py
%prg_python37%  core\geometry\simple\quadric\invoke.py
%prg_python37%  core\geometry\simple\plane\invoke.py
%prg_python37%  core\geometry\simple\paraboloid\invoke.py
%prg_python37%  core\geometry\simple\disc\invoke.py
%prg_python37%  core\geometry\simple\cylinder\invoke.py
%prg_python37%  core\geometry\simple\cone\invoke.py
%prg_python37%  core\geometry\simple\box\invoke.py
%prg_python37%  core\geometry\complex\invoke.py
%prg_python37%  core\camera\invert.py
%prg_python37%  core\geometry\simple\sphere\intersect.py
%prg_python37%  core\geometry\simple\image.py
%prg_python37%  core\camera\flat\hybrid.py
%prg_python37%  core\material\light\generator-invoke.py
%prg_python37%  core\camera\flat\general.py
%prg_python37%  core\render\framework.py
%prg_python37%  core\camera\focus-render.py
%prg_python37%  core\camera\focus-invoke.py
%prg_python37%  core\material\medium\exponential.py
%prg_python37%  core\geometry\simple\engine.py
%prg_python37%  core\light\dark_invoke.py
%prg_python37%  core\material\medium\constant.py
%prg_python37%  core\camera\cone-render.py
%prg_python37%  core\camera\cone-invoke.py
%prg_python37%  core\geometry\simple\camera.py
%prg_python37%  core\render\0scanner\block.py
%prg_python37%  core\render\2pierce\base.py
%prg_python37%  core\render\1pixel\base.py
%prg_python37%  core\geometry\blobby\affine.py
%prg_python37%  core\geometry\simple\0-sphere-main.py
%prg_python37%  core\light\_all_render.py
%prg_python37%  core\geometry\simple\_all_render.py
%prg_python37%  core\light\_all_invoke.py
%prg_python37%  core\geometry\simple\_all_invoke.py

pause


%prg_python37%  library\math\coord\coord4D.py
%prg_python37%  library\math\coord\coord3D.py
%prg_python37%  library\math\coord\coord2D.py
%prg_python37%  library\math\coord\cell3D.py
%prg_python37%  library\math\coord\cell2D.py
%prg_python37%  library\math\matrix\test.py
%prg_python37%  library\math\interval\test.py
%prg_python37%  library\math\affine\test.py
%prg_python37%  library\graph\color\test.py

pause


