#include "./congruent1d.hpp"
#include "./congruent2d.hpp"
#include "./sobol1d.hpp"
#include "./sobol2d.hpp"
#include "./standard1d.hpp"
#include "./table1d.hpp"
#include "./table2d.hpp"
#include "./vdc1d.hpp"
