#include "./grid.hpp"
#include "./kmeans.hpp"
#include "./hexagon.hpp"
#include "./vdc.hpp"
#include "./random.hpp"
#include "./sobol.hpp"
#include "./congruent.hpp"

#include "./pinwheel.hpp"
#include "./ld.hpp"
#include "./triangle.hpp"
#include "./poisson.hpp"
#include "./sunflower.hpp"
//#include "./general.hpp"
